### ISSUE TITLE
Add created_at, updated_at, deleted_at DateTime fields to all models

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#115]
### Requirements
- Future proofing.

**Comment by hurjun1995** [comment]
Why do we need deleted_at? Or how do we even have that value to deleted item in the first place? lol

**Comment by leesw98** [comment]
@hurjun1995 We need deleted_at because we don't want to actually didn't the data. We will simply mark them as deleted in case of future references are needed since these are supposedly sensitive data. Note: created_at, updated_at should be Datetime with default values, deleted_at would be Datetime with no default with null allowed.

**Comment by leesw98** [comment]
Still needs deleted_at along with soft_delete

**Comment by leesw98** [comment]
@gauravnv Also please update the timezones to use UTC.

**Comment by leesw98** [comment]
Also override update to update updated_at
