### ISSUE TITLE
CSV Parsing Front-end

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#14]
**This issue depends on #7.**

Once #7 is started, create file upload and submit button that requests to the back-end to parse the data to upload.

**Comment by leesw98** [comment]
Do this by extending the existing admin view. 

http://heyman.info/2011/jul/5/extending-templates-specific-django-app/

**Comment by leesw98** [comment]
https://stackoverflow.com/questions/37975156/how-to-manipulate-user-uploaded-files-in-django-without-saving-it

**Comment by michellehuh** [comment]
https://stackoverflow.com/questions/3780737/add-a-custom-button-to-a-django-applications-admin-page

**Comment by leesw98** [comment]
@michellehuh Push your local branch please.

**Comment by leesw98** [comment]
Reopen later if necessary.
