### ISSUE TITLE
Created_at value is always "now", not date specified in CSV file

### ISSUE THREAD

**Issue by hurjun1995** [CodeTheChangeUBC/reBOOT#155]
### Requirements
- Created_at value is always "now", not date specified in CSV file, whereas created_at_formatted has a correct value.
- Data_view query temporarily uses created_at_formatted to filter models; Need to change back to created_at when this issue is resolved.

**Comment by leesw98** [comment]
Resolved via updating the parser to set `created_at_formatted` on all models. Raises another issue #163
