### ISSUE TITLE
Database view and add

### ISSUE THREAD

**Issue by Csignore** [CodeTheChangeUBC/reBOOT#19]
1, When adding a new donation, donor_id is assigned automatically, we don't want that, we want to assign a specific donor_id to a donation; the same thing might happen for creating a new item
Also, if we ignore this problem, go ahead and add this donation, it complains about 'donation_id_id' cannot be null, which i think its the problem of 'list-filter' function.
2, Items cannot be modified

**Comment by Csignore** [comment]
<img width="829" alt="screen shot 2017-10-29 at 11 15 26 am" src="https://user-images.githubusercontent.com/25695476/32146809-857e0638-bc9a-11e7-8e1f-66ec5bb2254f.png">

**Comment by leesw98** [comment]
Current status of db

![screen shot 2017-10-29 at 12 39 15](https://user-images.githubusercontent.com/19914676/32147533-3b16ded8-bca6-11e7-8793-a9c894543652.JPG)

**Comment by ying-choi** [comment]
Fixed with #20
