### ISSUE TITLE
Testing CSV Parsing

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#27]
Check if the CSV file imported is valid and contains all the fields necessary to complete each entry.
Note: Some fields can be NULL.

If the file import isn't valid, the user should be alerted and redirected back.

Use [pytest-django](https://pytest-django.readthedocs.io/en/latest/)

Create dummy csv with wrong fields as well as correct fields to test each file.

- [ ] Donor
- [ ] Donation
- [ ] Item

**Comment by leesw98** [comment]
Hold off until #15 is done.

**Comment by gauravnv** [comment]
For anyone working on this issue, use Pytest.

**Comment by leesw98** [comment]
Should be automatically handled by PostgreSQL's strict field types.
(Aka parsing will throw error when the fields are incorrect)
