### ISSUE TITLE
DB Model Unit Testing

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#28]
- Test models in terms of inputting valid inputs
- Test models in terms of inputting invalid inputs. Especially...
  - Phone Number
  - Email
  - Postal Code
  - Tax Receipt No
  - Batch (?)

Use [pytest-django](https://pytest-django.readthedocs.io/en/latest/)

I suggest using PyTest or Django Test; Create a test DB just for testing and do the tests there. 

- [ ] Donor
- [ ] Donation
- [ ] Item

**Comment by gauravnv** [comment]
Use PyTest.

**Comment by leesw98** [comment]
- [ ] Donor

- [ ] Donation

- [ ] Item

**Comment by Csignore** [comment]
gauravnv, u know how to use PyTest? Do u need a hand on this issue? I wanna learn PyTest.

**Comment by gauravnv** [comment]
I am learning. We can work on it together. It's tedious but useful.

**Comment by leesw98** [comment]
I think [pytest-django](https://pytest-django.readthedocs.io/en/latest/) would be the best option for. It works similar to jUnit testing in that you can reset back to a before state. Same goes for #27

**Comment by leesw98** [comment]
Hold off until #56 and the data integrity level is settled.
