### ISSUE TITLE
Remove "not categorized" device type

### ISSUE THREAD

**Issue by yuubd** [CodeTheChangeUBC/reBOOT#313]
**Context**
If an item is imported and its device type is not in db, it displays the type as "not categorized - {ITEM_DESCRIPTION}". 

**Requirement**
Instead, we want "{MISCELLANEOUS} {ITEM_DESCRIPTION}". So, in the UI it displays "Others - {ITEM_DESCRIPTION}".

**Comment by bwdmonkey** [comment]
Closed by #314
