### ISSUE TITLE
Implement Django Admin Site Table View

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#4]
If you currently look at the data tables, it will represent entries as XXXX Object (ie. Donor Object) which isn't very useful. I believe this is solved using the list_display function from Django. 

https://docs.djangoproject.com/ko/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display

**Comment by leesw98** [comment]
Checkout [admin-db-view](https://github.com/CodeTheChangeUBC/reBOOT/tree/admin-db-view)

**Comment by ying-choi** [comment]
Latest fixes in yy-branch.

**Comment by ying-choi** [comment]
Fixed with Omar's #20
