### ISSUE TITLE
Handle Heroku request timeout

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#45]
When we use Heroku eventually for the server hosting, we will need to handle request timeout of maximum 30 seconds. 👎 

This means that we will need to handle our CSV parser. I can get the server to continuously handle the CSV parsing in the background but we need to redirect the user to a page so that they can wait as the CSV parsing continues. We don't want the user to see the request timeout error.

I am open to any suggested solutions.

Also checkout [rebootcanada.herokuapp.com](https://rebootcanada.herokuapp.com). This is still using our dev db so don't worry about errors.

**Comment by leesw98** [comment]
`git fetch -a -p`

`git checkout production`

**Comment by omar2535** [comment]
Redirect to a page and have a progress bar while parsing as well?

**Comment by leesw98** [comment]
If that's possible, that would be great. I am uncertain how we will do that since we need to execute the csv_parse() function prior to return a HTTP response. I'm looking into a way that allows to parse after returning the response.

**Comment by omar2535** [comment]
Async functionality? https://stackoverflow.com/questions/32536799/python-django-asynchronous-request-handling

**Comment by leesw98** [comment]
Welp, that did it. 👍

I had to use tornado (async) workers instead of sync workers. It still leads to timeout but it does return the files at least.
