### ISSUE TITLE
Optimize "create" queries by handling in bulk

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#49]
Optimize query handling by using bulk_create

https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create

**Comment by leesw98** [comment]
`git checkout batch-sql`

**Comment by leesw98** [comment]
@omar2535 
Can you take the batch parser and make it into the shared task? Also, perhaps we could do something similar with pdf generation where we send the request to process queue and return the zip file to avoid timeout.

**Comment by omar2535** [comment]
@leesw98 Ok

**Comment by leesw98** [comment]
Separated into new issue
