### ISSUE TITLE
Stricter data integrity in CSV parser

### ISSUE THREAD

**Issue by leesw98** [CodeTheChangeUBC/reBOOT#56]
### TODO
- Check if the contents upholds some level of data integrity
  - ie) Don't allow "xxxxxxx" in telephone number; It should be NULL or just real numbers
  - Donor Name should never be empty; Either real name or anon
 
We can hash out further details at a later point if needed.

**Comment by Csignore** [comment]
There are some phone numbers that have extensions. The database about the phone number fields need to be changed and migrated.
